# Generated by Django 2.1.7 on 2019-03-02 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_main', '0003_rental'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartment',
            options={'managed': True, 'verbose_name': 'Квартиру', 'verbose_name_plural': 'Квартиры'},
        ),
        migrations.AlterModelOptions(
            name='rental',
            options={'managed': True, 'verbose_name': 'Арену квартиры', 'verbose_name_plural': 'Аренда квартиры'},
        ),
        migrations.AlterModelOptions(
            name='subscribers',
            options={'managed': True, 'verbose_name': 'Риелтора', 'verbose_name_plural': 'Риелторы'},
        ),
        migrations.AlterModelTable(
            name='apartment',
            table='',
        ),
        migrations.AlterModelTable(
            name='rental',
            table='',
        ),
        migrations.AlterModelTable(
            name='subscribers',
            table='',
        ),
    ]
