# Generated by Django 2.1.7 on 2019-03-12 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_main', '0004_auto_20190302_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='text',
            field=models.CharField(blank=True, help_text='Enter field documentation', max_length=200),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='title',
            field=models.CharField(blank=True, help_text='Enter field documentation', max_length=200),
        ),
    ]
