# Generated by Django 2.1.7 on 2019-03-12 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_main', '0005_auto_20190312_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='price',
            field=models.FloatField(default=0.0, help_text='цена обьекта'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='text',
            field=models.CharField(blank=True, help_text='Адрес обьекта', max_length=200),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='title',
            field=models.CharField(blank=True, help_text='введите название обьекта', max_length=200),
        ),
    ]
